"""Create initial tables

Revision ID: 5abb2b490098
Revises: 
Create Date: 2026-06-26 13:23:58.625875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abb2b490098'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('international_number', sa.String(), nullable=False),
    sa.Column('callsign', sa.String(), nullable=True),
    sa.Column('marking', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('owner_contact', sa.String(), nullable=True),
    sa.Column('captain_name', sa.String(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('tonnage', sa.Float(), nullable=True),
    sa.Column('draft', sa.Float(), nullable=True),
    sa.Column('engine_power', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ships_id'), 'ships', ['id'], unique=False)
    op.create_index(op.f('ix_ships_international_number'), 'ships', ['international_number'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holder_name', sa.String(), nullable=False),
    sa.Column('holder_egn', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_minor', sa.Boolean(), nullable=True),
    sa.Column('is_pensioner', sa.Boolean(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('telk_decision_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_table('amateur_catches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('catch_date', sa.Date(), nullable=False),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('amount_kg', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amateur_catches_id'), 'amateur_catches', ['id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspector_name', sa.String(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('violation_found', sa.Boolean(), nullable=True),
    sa.Column('violation_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_table('permits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_reason', sa.String(), nullable=True),
    sa.Column('holder_name', sa.String(), nullable=False),
    sa.Column('captain_name', sa.String(), nullable=True),
    sa.Column('gear_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permits_id'), 'permits', ['id'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id')
    )
    op.create_index(op.f('ix_fines_id'), 'fines', ['id'], unique=False)
    op.create_table('fishing_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fishing_trips_id'), 'fishing_trips', ['id'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('gear_used', sa.String(), nullable=True),
    sa.Column('catch_amount_kg', sa.Float(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['fishing_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_id'), 'log_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entries_id'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_fishing_trips_id'), table_name='fishing_trips')
    op.drop_table('fishing_trips')
    op.drop_index(op.f('ix_fines_id'), table_name='fines')
    op.drop_table('fines')
    op.drop_index(op.f('ix_permits_id'), table_name='permits')
    op.drop_table('permits')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_amateur_catches_id'), table_name='amateur_catches')
    op.drop_table('amateur_catches')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_ships_international_number'), table_name='ships')
    op.drop_index(op.f('ix_ships_id'), table_name='ships')
    op.drop_table('ships')
    # ### end Alembic commands ###
